# -*- coding: utf-8 -*-
"""text-to-video.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZT2WTUY1D9sCKEybBopBU1esMupHDDN8
"""

!pip install --upgrade diffusers[torch]

import torch
from diffusers import DiffusionPipeline
from diffusers.utils import export_to_video

# Initialize the pipeline with the pretrained model
pipe = DiffusionPipeline.from_pretrained("damo-vilab/text-to-video-ms-1.7b", torch_dtype=torch.float16, variant="fp16")
pipe = pipe.to("cuda")

#  Enable CPU offload and VAE slicing for memory optimization
pipe.enable_model_cpu_offload()
pipe.enable_vae_slicing()

# Generate video frames
prompt = "Two cats are playing in a garden."
video_frames = pipe(prompt, num_frames=64).frames[0]

#  Export frames to video
video_path = export_to_video(video_frames)

 Download and play video in any video player
# The video will be generated in the tmp folder in colab.
print(video_path)

#  Generate video frames
prompt = "A car near to park."
video_frames = pipe(prompt, num_frames=64).frames[0]

#  Export frames to video
video_path = export_to_video(video_frames)

#  Download and play video in any video player
# The video will be generated in the tmp folder in colab.
print(video_path)

